# Generated by Django 5.2.8 on 2025-12-01 12:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.CharField(default='content', max_length=50, primary_key=True, serialize=False)),
                ('hero', models.JSONField(default=dict)),
                ('testimonials', models.JSONField(default=list)),
                ('sponsors', models.JSONField(default=list)),
                ('footer', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
                'db_table': 'homepage_content',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('payment_details', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('edit', 'Edit'), ('skip', 'Skip')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Changes made during edit')),
                ('payout_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('skip_data_correct', models.BooleanField(default=False)),
                ('skip_feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'review_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.CharField(default='config', max_length=50, primary_key=True, serialize=False)),
                ('payout_rate_default', models.DecimalField(decimal_places=4, default=0.002, max_digits=10)),
                ('skip_threshold_default', models.IntegerField(default=5)),
                ('lock_timeout_sec', models.IntegerField(default=180)),
                ('finalize_review_count', models.IntegerField(default=3)),
                ('gold_skip_correct_threshold', models.IntegerField(default=5)),
                ('max_unchecked_skips_before_prompt', models.IntegerField(default=2)),
                ('available_languages', models.JSONField(default=list, help_text='List of {code, name} objects')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_config',
            },
        ),
    ]
